export const CREATE_PEDIDOS_TABLE = `
CREATE TABLE IF NOT EXISTS pedidos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  fecha_entrega TEXT NOT NULL,
  nombre TEXT NOT NULL,
  precio_final REAL NOT NULL,
  monto_abonado REAL NOT NULL,
  descripcion TEXT,
  imagen TEXT,
  productos TEXT NOT NULL
);
`;

export const CREATE_SABORES_TABLE = `
CREATE TABLE IF NOT EXISTS sabores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL UNIQUE,
  tipo TEXT NOT NULL,
  activo INTEGER DEFAULT 1
);
`;

export const CREATE_RELLENOS_TABLE = `
CREATE TABLE IF NOT EXISTS rellenos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL UNIQUE,
  activo INTEGER DEFAULT 1
);
`;

export const DROP_PEDIDOS_TABLE = `DROP TABLE IF EXISTS pedidos;`;
export const DROP_SABORES_TABLE = `DROP TABLE IF EXISTS sabores;`;
export const DROP_RELLENOS_TABLE = `DROP TABLE IF EXISTS rellenos;`; 